name = "openwrt-bot"
main = "src/index.js"
compatibility_date = "2026-06-29"
workers_dev = false
preview_urls = false

[observability]
enabled = true

[observability.logs]
destinations = [ "honeycomb-logs" ]

[observability.traces]
enabled = true
destinations = [ "honeycomb-traces" ]

[placement]
hostname = "api.github.com"

[triggers]
crons = ["30 5 * * *"]

[vars]
DEPLOY_HASH = "unknown"
DEPLOY_DATE = "unknown"
