name: Run Unit Tests & Verify Build

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run Unit Tests
        run: npm test
        working-directory: cloudflare-worker
        env:
          FORCE_COLOR: 1

      - name: Dry Run Wrangler Deploy
        run: npx wrangler deploy --dry-run
        working-directory: cloudflare-worker
